version: '3.6'
services:
    shop:
      build: .
      ports:
        - "5000:5000"
      volumes:
        - ./src:/shop/src
      depends_on:
        [postgres]
    postgres:
      image: postgres:13.4
      healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "test_db", "-U", "root" ]
        timeout: 45s
        interval: 10s
        retries: 10
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - APP_DB_NAME=postgres
      volumes:
        - ./db:/docker-entrypoint-initdb.d/
      ports:
        - "5432:5432"
